export const GAME_CONFIG = {
  camera: {
    fov: 74,
    near: 0.1,
    far: 170,
  },
  fog: {
    color: 0xe7e5dc,
    near: 40,
    far: 165,
  },
  player: {
    height: 1.72,
    radius: 0.35,
    walkSpeed: 3.2,
    sprintSpeed: 5.1,
    jumpVelocity: 5.25,
    gravity: 15.4,
    interactionRange: 1.85,
    staminaMax: 100,
    staminaDrainPerSecond: 22,
    staminaRecoverPerSecond: 24,
    healthMax: 100,
    healthRecoverPerSecond: 8,
  },
  flashlight: {
    intensity: 1.5,
    distance: 18,
    angle: Math.PI / 7,
    penumbra: 0.48,
  },
  monster: {
    radius: 0.4,
    patrolSpeed: 1.4,
    chaseSpeed: 7.2,
    retreatSpeed: 3.15,
    detectionRange: 11.5,
    focusedSightRange: 13.5,
    rearSenseRange: 2.4,
    nearRange: 4.2,
    visionHalfAngle: Math.PI / 10,
    attackRange: 1.55,
    damagePerHit: 24,
    jumpScareDuration: 1.08,
    jumpScareCooldown: 3,
  },
  dust: {
    count: 120,
  },
} as const;
